development:
  adapter: postgresql
  host: localhost
  database: maas_development
  username: postgres
  password:

#test:
  #adapter: postgresql
  #host: localhost
  #database: maas_test
  #username: postgres
  #password:

#production:
  #adapter: postgresql
  #host: localhost
  #database: maas_production
  #username: postgres
  #password:
